version: "3.8"
services:
  role-management-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=gungadhisanjaya
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=role_management_service
    depends_on:
      - db

    command: >
      sh -c "
      echo 'Waiting for MySQL to be ready';
      while ! nc -z db 3306; do sleep 1; done;
      echo 'MySQL ready';
      python run.py"
    volumes:
      - .:/app
    networks:
      - microservice-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: role_management_service
    ports:
      - "3309:3306"
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
