version: "3.8"
services:
  role-management-service:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
