"""changing coloumn name in rolepermission

Revision ID: d3af567215ee
Revises: 2eaea8b7f884
Create Date: 2025-05-12 13:02:51.276314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3af567215ee'
down_revision = '2eaea8b7f884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('permission_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('roles_permissions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('roles_permissions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.drop_column('permissions_id')
        batch_op.drop_column('roles_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('permissions_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_permissions_ibfk_1', 'permissions', ['permissions_id'], ['id'])
        batch_op.create_foreign_key('roles_permissions_ibfk_2', 'roles', ['roles_id'], ['id'])
        batch_op.drop_column('permission_id')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
